### ISSUE TITLE
Not support latest Intellij

### ISSUE THREAD

**Issue by cfanboy** [KartanHQ/intellij-hardhat#290]
### Describe the bug

The plugin does not support the latest version - Build #IU-233.11799.241

**Comment by PerunPrime** [comment]
11.12.23 - The plugin still not supported by PHPstorm - Build #PS-233.11799.232
![image](https://github.com/KartanHQ/intellij-hardhat/assets/17202595/91f932d6-280f-4c14-afae-ecd5f7472608)

**Comment by cliffhall** [comment]
Same with Webstorm. 
<img width="829" alt="Screenshot 2023-12-21 at 10 15 19 AM" src="https://github.com/KartanHQ/intellij-hardhat/assets/871933/90889ab0-e164-4981-85d3-b12d3945d21e">

**Comment by nekofar** [comment]
I've already tested and updated it. It should be available in the next release.

**Comment by emkman** [comment]
@nekofar the Jetbrains marketplace still shows [1.2.26](https://plugins.jetbrains.com/plugin/18551-hardhat/versions/stable/453442) as the latest version. Were 1.2.27 and 1.2.28 not published?

**Comment by cliffhall** [comment]
I wonder what the process is for getting JetBrains to recognize the latest version. This seems like a gap in tooling. We super duper need this.

**Comment by emkman** [comment]
> I wonder what the process is for getting JetBrains to recognize the latest version. This seems like a gap in tooling. We super duper need this.

It's possible the latest releases are not packaged properly because when I try to Load from Disk using the zip it fails.
