### ISSUE TITLE
Incompatible with JetBrains 2024.1 versions

### ISSUE THREAD

**Issue by JamesWilson0913** [KartanHQ/intellij-hardhat#344]
### Describe the bug

The v1.2.26 is incompatible with the latest JetBrains production, e.g. WebStorm, IntelliJ, etc.

**Comment by dtourassis** [comment]
Any updates on this matter?

**Comment by cliffhall** [comment]
I just updated my Jetbrains Webstorm IDE to 2024.1 and first message was:

> Plugin 'Hardhat' (version '1.2.26') is not compatible with the current version of the IDE, because it requires build 233.* or older but the current build is WS-241.15989.105

**cue sad trumpet**

**Comment by cliffhall** [comment]
@nekofar I noticed Hardhat just dropped a new 2.22.4 version 11 hours a go, so I thought I'd check in on this plugin. Is this project still supported?

**Comment by cliffhall** [comment]
Hold up, we still need this plugin!

It's starting to seem as if the project has been abandoned. We could fork it and try to get it into the Jetbrains system, but I don't know if that would work.

I'll try to get Hardhat and Jetbrains looking here to see what we can do to recover this plugin from the grave. 🪦

**Comment by arne-fuchs** [comment]
@cliffhall @dtourassis @slvrfn 
### Working fork here
Hey I am running a fork since last year to implement code completion for Javascript in the Hardhat plugin.
I've read this issue and **made the plugin IU 2024.1 compatible**: [You can find it here](https://github.com/arne-fuchs/intellij-hardhat/releases/tag/1.3.0-beta.3)

Please keep in mind, that there are additional features that might be unstable at the moment. If you have any trouble or suggestions please open an issue there.

**Comment by arne-fuchs** [comment]
I'd had no problem maintaining this repo, but I'd need to have access to the publish token for the marketplace so I can post regular updates directly to it.

**Comment by cliffhall** [comment]
> I'd had no problem maintaining this repo, but I'd need to have access to the publish token for the marketplace so I can post regular updates directly to it.

@arne-fuchs awesome. From repos alone It would seem only [nekofar](https://github.com/nekofar) could swing that. There is a website and email address at [KartanHQ](https://github.com/KartanHQ), this repo's org page. I sent a ping back in May with no response. nekofar's profile is still extremely active daily, but he has a huge number of projects and I know what its like to triage a seemingly endless backlog of email and tasks, so zero judgement, just info.

**Comment by arne-fuchs** [comment]
IntelliJ 2024.2 has just been released.
I've updated the plugin: [1.3.0-beta.4 for IU 2024.2](https://github.com/arne-fuchs/intellij-hardhat/releases/tag/1.3.0-beta.4)

**Comment by Dinuz** [comment]
Hey @cliffhall I tried to ping him on twitter too! Hope he gets it:)

**Comment by arne-fuchs** [comment]
@Dinuz I've even wrote a mail to KartanHQ
