### ISSUE TITLE
No new releases for a while in JetBrains plugin marketplace

### ISSUE THREAD

**Issue by ChmilevFA** [KartanHQ/intellij-hardhat#78]
**Describe the bug:**
for a while plugin was not updated in official JetBrains marketplace which already make some problems for newer JetBrains products.
![image](https://user-images.githubusercontent.com/17650184/174876067-0e3b95ad-e1f6-4b68-87e0-468c09cfc623.png)

**Steps to reproduce:** 
Tested with:
* WebStorm 2022.1.2 (latest at the moment of writing)
* IntelliJ IDEA Ultimate 2022.1.2 (latest at the moment of writing)

**Comment by nekofar** [comment]
It's going to be available in the marketplace in a couple of hours.

**Comment by Dinuz** [comment]
@nekofar I think we got back the issue:)
The plugin is not compatible with the latest release.
Check the messages:

![Screen Shot 2022-12-07 at 2 18 33 PM](https://user-images.githubusercontent.com/1139472/206275369-4f24f44a-b58e-423f-8541-152b9c2797a0.png)


![Screen Shot 2022-12-07 at 2 19 18 PM](https://user-images.githubusercontent.com/1139472/206275493-45dd8503-e8a4-4243-9d48-99c57fed8864.png)

The build changed from 222 to 223, so the plugin must be update
![Screen Shot 2022-12-07 at 2 19 37 PM](https://user-images.githubusercontent.com/1139472/206275562-2ebe53f9-1885-4e7d-b2ce-0c7dbdc8b253.png)

How I can help?
